-- Generated by Monique — https://github.com/ToRvaLDz/monique

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.dsp.exec_cmd("sed -i 's/disabled = 1,/disabled = 0,/g' ~/.config/hypr/monitors.lua")
