# ######## Window rules ########
# windowrule = opacity 0.89 override 0.89 override, .* # Applies transparency to EVERY WINDOW
windowrule = float on, match:title ^(Steam)$
windowrule = float on, match:title ^Calculator$
windowrule = float on, match:title ^(guifetch)$ # FlafyDev/guifetch
windowrule = float on, match:title ^(Android Emulator)(.*)$
windowrule = float on, match:title ^(Emulator)(.*)$
windowrule = float on, match:title ^(blueman-manager)(.*)$
windowrule = float on, match:title ^(Network Displays)(.*)$
windowrule = float on, match:title ^(Volume Control)(.*)$
windowrule = tile on, match:title .*(Microsoft Teams)(.*)
windowrule = tile on, match:title .*(Outlook)(.*)
windowrule = size 80% 80%, match:title ^(Volume Control)(.*)$
windowrule = tile on, match:class (dev.warp.Warp)
windowrule = float on, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
#windowrule = center, match:title ^(Open File)(.*)$
windowrule = center on, match:title ^(Select a File)(.*)$
windowrule = center on, match:title ^(Choose wallpaper)(.*)$
windowrule = center on, match:title ^(Open Folder)(.*)$
windowrule = center on, match:title ^(Save As)(.*)$
windowrule = center on, match:title ^(Library)(.*)$
windowrule = center on, match:title ^(File Upload)(.*)$

# Dialogs
windowrule=float on,match:title ^(Open File)(.*)$
windowrule=float on,match:title ^(Select a File)(.*)$
windowrule=float on,match:title ^(Choose wallpaper)(.*)$
windowrule=float on,match:title ^(Open Folder)(.*)$
windowrule=float on,match:title ^(Save As)(.*)$
windowrule=float on,match:title ^(Library)(.*)$
windowrule=float on,match:title ^(File Upload)(.*)$

# Tearing
#windowrulev2=immediate,.*\.exe
windowrule=immediate on,match:class (steam_app)

# No shadow for tiled windows
#windowrule = noshadow on,floating:0

# ######## Layer rules ########
#layerrule = xray 1, .*
# layerrule = no_anim on, match:namespace .*
layerrule = no_anim on, match:namespace walker
layerrule = no_anim on, match:namespace selection
layerrule = no_anim on, match:namespace overview
layerrule = no_anim on, match:namespace anyrun
layerrule = no_anim on, match:namespace indicator.*
layerrule = no_anim on, match:namespace osk
layerrule = no_anim on, match:namespace hyprpicker
#layerrule = blur, shell:*
#layerrule = ignorealpha 0.6, shell:*

#layerrule = blur, gtk-layer-shell
#layerrule = ignorezero, gtk-layer-shell
#layerrule = blur, launcher
#layerrule = ignorealpha 0.5, launcher
#layerrule = blur, notifications
#layerrule = ignorealpha 0.69, notifications

